apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    namespace: {{ .values.spec.destination.namespace}}
    server: {{ .values.spec.destination.server }}

  project: default

  source:
    repoURL: {{ .values.spec.source.repoURL}}
    targetRevision: HEAD
    path: test-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true